Kafka Kasten
kastendevhub/kastendevhub.github.io pull request #14
Opened 2024-06-03 12:17 UTC by michaelcourcy

In this blog we show how to use Kasten to restore a complex and stateful application generated by the kafka strimzi operator

2024-06-04 17:16 UTC, smohandassk10 commented on _posts/2024-06-03-kasten-and-strimzi-kafka.markdown
> +From a Kasten perspective it's just another classical Kubernetes application, however the Kafka architecture does require some finesse in restoration. Firstly it's important to understand what Kafka
Firstly -> First

2024-06-04 17:17 UTC, smohandassk10 commented on _posts/2024-06-03-kasten-and-strimzi-kafka.markdown
> +*  When the operator finds a namespace with a Kafka configuration, it will deploy that configuration into the end namespace and manage the spinning up of pods, creation of PVCs and creation of all se
manage the spinning up of pods -> manage the lifecycle of the pods

2024-06-04 17:20 UTC, smohandassk10 commented on _posts/2024-06-03-kasten-and-strimzi-kafka.markdown
> +Assuming we have a working cluster with a default storageclass, HELM installed and kubectrl access to the cluster we can go ahead and install the Strimzi operator:
Assuming we have a working cluster with a default storageClass, HELM installed and kubectrl access to the cluster, let's install the Strimzi operator:

2024-06-04 17:24 UTC, smohandassk10 requested changes
Requested a few minor changes. Rest looks good.

2024-06-05 08:20 UTC, michaelcourcy commented
Thanks for the suggestions @smohandassk10 !

2024-06-05 08:20 UTC, merged